### ISSUE TITLE
Create a Show Model

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio-api#1]
Our shows model should have the following:
# Shows
* ID
  * Type: Integer
* Name
  * Type: String
* User IDs
  * Type: Integer Array
* Description
  * Type: String
* Genre
  * Type: String
* Image
  * Type: String
* Start Time
  * Type: Time
* End Time
  * Type: Time

After defining the model, verify your model works with a seeding script similar to Daily Bruin's Sources seeding [script](https://github.com/daily-bruin/sources/blob/master/scripts/create-data.ts)

**Comment by binerys** [comment]
Completed by #7
